project:
  type: website

website:
  favicon: images/favicon.png
  title: "user 2025"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

execute:
  echo: true
  
highlight-style: atom-one


